insert into documents(url, title, publication_date, modified_date, author, publisher, notes) values
  ('https://reducing-suffering.org/how-much-direct-suffering-is-caused-by-various-animal-foods/','How Much Direct Suffering Is Caused by Various Animal Foods?','2007-01-01',NULL,'Brian Tomasik','Reducing Suffering','In this lengthy essay, Brian Tomasik compares the amount of direct animal suffering caused by various animal foods. He notes that the animal suffering caused per kg varies wildly, with an estimate that farmed catfish may cause 20,000 times as much direct suffering per kg as milk'),
  ('http://everydayutilitarian.com/essays/why-eat-less-meat/','Why Eat Less Meat?','2013-06-06',NULL,'Peter Hurford',NULL,'Peter Hurford, in this post on his own blog, writes about his ethical motive for going completely vegetarian as of the previous Thanksgiving (November 2012). His chain of reasoning is: animals can suffer, factory farming causes considerable suffering, vegetarianism can make a difference, and vegetarianism is easier than you think. He concludes with a challengeto people to try being vegetarian for a while, or least try to be reducetarian (eat less meat) or eat meat from bigger animals, resulting in less suffering per unit food consumed'),
  ('https://meteuphoric.com/2014/11/21/when-should-an-effective-altruist-be-vegetarian/','When should an Effective Altruist be vegetarian?','2014-11-21',NULL,'Katja Grace',NULL,'Katja Grace describes her thoughts on why trying to be vegetarian may not be a good idea for most effective altruists. In particular, she argues that the relevant comparison is not whether the personal cost of forgoing meat is exceeded by the benefits of being vegetarian (in terms of reduced animal suffering or reduced animal deaths). Rather, the relevant comparison is between the maximum benefit that can be achieved for the same cost. For instance, in many cases, eating more frugally and donating the savings to a suitable charity may generate more value for the same personal cost. The post attracts 44 comments, many of which push back against the claims in the post. Commenters include David Pearce, Brian Tomasik, Boris Yakubchik, and Magnus Vinding. Some of the points of pushback include: the relative value of human and animal suffering, the probability that animals are conscious, the health effects of vegetarianism, and the value of vegetarians as early adopters who help create a market for vegetarian products'),
  ('https://forum.effectivealtruism.org/posts/WDiBMR2eXmNKSRjvd/should-i-be-vegan','Should I be vegan?','2015-05-17',NULL,'Jess Whittlestone','Effective Altruism Forum','Jess Whittlestone','Jess Whittlestone, who is vegetarian and consumes dairy and eggs, grapples with the question of whether to go fully vegan. She offers the following reasons for going vegan: (1) Impact of her diet on animal suffering, (2) Not wanting to be part of the factory farming enterprise, (3) Signalling and encouraging others. She offers the following arguments against: (1) Inconvenience, enjoyment, willpower, (2) Health, (3) No need to be all-or-nothing. She then asks the commenters if there are other considerations she is missing. In the comments, Paul Christiano, Brian Tomasik, Peter Hurford, and others argue against lumping together milk and eggs, and suggest a focus on cutting out eggs (i.e., becoming a lacto-vegetarian). Rob Wiblin also notes that he switched from veganism to lacto-vegetarianism + having mussels. Tom Ash notes in the comments that he is in a similar situation as Jess. Michael Dickens argues that being vegan for a few months will make it easier to be vegan in the long term'),
  ('http://lukemuehlhauser.com/storeable-convenient-vegn-meal-options/','Storeable, convenient veg*n meal options','2017-10-04',NULL,'Luke Muehlhauser',NULL,'After writing his animal consciousness report http://www.openphilanthropy.org/2017-report-consciousness-and-moral-patienthood Luke Muehlhauser has strived to be more reducetarian, i.e., reduce animal products in his diet. He links to a spreadsheet https://docs.google.com/spreadsheets/d/1kZ6IVxrCRuMLrJ_dC03fvnCIClBGzDBj0epYWS38bi4/edit#gid=0 of his findings of good options for people seeking vegetarian foods. Muehlhauser is based in the San Francisco Bay Area, so the items in the list may have limited utility in other locations'),
  ('https://slatestarcodex.com/2015/01/04/ethics-offsets/','Ethics offsets','2015-01-04',NULL,'Scott Alexander','Slate Star Codex','On his widely read blog, Scott Alexander discusses the concept of ethics offsets: donating enough to offset the ethical damage of one''s actions. He discusses as an example being a meat-eater who donates enough to convert multiple people to vegetarianism, and explains a few ways he feels weird about this: a sense of duping others and a concern about universalizability (if everybody did it, it wouldn''t make sense). He discusses possible responses to both'),
  ('https://qz.com/493090/we-need-more-meat-eating-animal-rights-advocates/','We need more meat-eating animal-rights advocates','2015-09-02',NULL,'Brian Kateman','Quartz','Brian Kateman of the Reducetarian Foundation explains his reasons for advocating reducetarianism rather than strict veganism'),
  ('https://slatestarcodex.com/2015/09/23/vegetarianism-for-meat-eaters/','Vegetarianism for meat-eaters','2015-09-23',NULL,'Scott Alexander','Slate Star Codex','Scott Alexander suggests two ways for meat eaters to grapple with their impact on animal suffering: (1) Eat meat from larger animals, which causes less suffering per calorie (in slogan form: "eat beef, not chicken"), (2) Use ethics offsets by donating to animal charities');
  
  
